# Auto-generated by build_mie286_vectors.R — do not edit by hand.
# Regenerate: Rscript build_mie286_vectors.R (wd = code/)
# Vectors share one element per participant; index i aligns across all names below.
# Names: participant, duration_sec_numerical, duration_sec_spatial_color,
#   area_off_px2_numerical, area_off_px2_spatial_color, gender, avg_gaming_hours_per_day

participant <- c("Aayush", "Derek Chen", "Ines", "Michael", "Nareen", "Rahi", 
"Ricky", "alison", "belinda", "bruce", "david", "emily", "eric", 
"han", "heidi", "j chen", "jadon t", "katherine", "lawrence", 
"mani", "mikeli", "pranav", "rachel", "robyn", "selina", "shiv", 
"soham", "srishti", "sumedhaa", "vanessa", "victoria", "yiran"
)

duration_sec_numerical <- c(163, 92, 93, 50, 43, 80, 62, 76.71, 102, 161.5, 38.76, 84.09, 
126.85, 69.38, 130.19, 55.58, 92, 154.49, 23.53, 56.31, 63.17, 
69.33, 52.08, 97.35, 65, 74.22, 123.48, 161.98, 115, 57.76, 64.95, 
37.15)

duration_sec_spatial_color <- c(150, 76, 111, 40, 43.28, 63, 60, 78.86, 65, 81.12, 56.22, 52.26, 
104.86, 67.53, 98.81, 59.7, 77, 139.3, 38.13, 108.48, 66.41, 
87.72, 52.17, 82.74, 81, 42.54, 75.33, 124.43, 132, 47.32, 67.41, 
32.59)

area_off_px2_numerical <- c(1888.4, 2742.2, 2245.3, 4513.4, 4209.1, 3708.4, 3396.1, 2877.4, 
3273.6, 2651.2, 4471.7, 2881.3, 1653.6, 2402.3, 2595, 2765.8, 
2899.8, 2405.2, 5404.7, 2353.1, 3585.2, 2561.1, 3857.7, 2180.5, 
2960.3, 2862.7, 2486.3, 1733.3, 2711.5, 3748.8, 3664.6, 4099.3
)

area_off_px2_spatial_color <- c(2164.8, 2748.5, 2122, 4449.8, 3437.6, 2911.1, 2937.3, 2929.4, 
3257.7, 3330.7, 3969.2, 3724.1, 1913.8, 2285.2, 2725.3, 2341, 
3154.9, 2572.7, 4137.7, 1935.1, 3394.3, 2105.2, 3223, 2318, 2405.1, 
3814.5, 2971.5, 2077, 2548.2, 3583, 3264.7, 6143)

gender <- c("man", "man", "woman", "man", "woman", "man", NA, "woman", 
"woman", "man", "man", "woman", "man", "man", "woman", "woman", 
"man", "woman", "man", "man", "man", "man", "woman", "woman", 
"woman", "man", "man", "woman", "woman", "woman", "woman", "woman"
)

avg_gaming_hours_per_day <- c(0, 0, 0, 4, 0, 1.5, NA, 1.5, 4, 1.5, 1.5, 0, 0, 0, 0, 1.5, 
0, 1.5, 4, 0, 4, 0, 0, 4, 0, 4, 0, 1.5, 0, 4, 0, 0)
