# Auto-generated by build_mie286_vectors.R — paired rows (same participant order).
# To refresh after new CSV data: Rscript build_mie286_vectors.R

participant <- c("Aayush", "Derek Chen", "Ines", "Michael", "Nareen", "Rahi", 
"Ricky", "alison", "bruce", "eric", "han", "j chen", "jadon t", 
"katherine", "lawrence", "mikeli", "pranav", "rachel", "robyn", 
"selina", "shiv", "soham", "sumedhaa", "vanessa", "victoria", 
"yiran")

duration_sec_numerical <- c(163, 92, 93, 50, 43, 80, 62, 76.71, 161.5, 126.85, 69.38, 55.58, 
92, 154.49, 23.53, 63.17, 69.33, 52.08, 97.35, 65, 74.22, 123.48, 
115, 57.76, 64.95, 37.15)

duration_sec_spatial_color <- c(150, 76, 111, 40, 43.28, 63, 60, 78.86, 81.12, 104.86, 67.53, 
59.7, 77, 139.3, 38.13, 66.41, 87.72, 52.17, 82.74, 81, 42.54, 
75.33, 132, 47.32, 67.41, 32.59)

area_off_px2_numerical <- c(1888.4, 2742.2, 2245.3, 4513.4, 4209.1, 3708.4, 3396.1, 2877.4, 
2651.2, 1653.6, 2402.3, 2765.8, 2899.8, 2405.2, 5404.7, 3585.2, 
2561.1, 3857.7, 2180.5, 2960.3, 2862.7, 2486.3, 2711.5, 3748.8, 
3664.6, 4099.3)

area_off_px2_spatial_color <- c(2164.8, 2748.5, 2122, 4449.8, 3437.6, 2911.1, 2937.3, 2929.4, 
3330.7, 1913.8, 2285.2, 2341, 3154.9, 2572.7, 4137.7, 3394.3, 
2105.2, 3223, 2318, 2405.1, 3814.5, 2971.5, 2548.2, 3583, 3264.7, 
6143)
